---
title: "alex_reefcheck_fish"
format: html
---

Packages

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(gtable)
library(grid)
library(scales)
library(tidyverse)
library(readr)
library(ggpattern)
```

initial data import

```{r}
fish_data <- read_csv("C:/R Projects/2025/port-report/data/Fish.csv")
kelp_data <- read_csv("C:/R Projects/2025/port-report/data/Kelp.csv")
invert_data <- read_csv("C:/R Projects/2025/port-report/data/Inverts.csv")
```

initial cleaning

```{r}
select_fish_data <- fish_data %>%
  mutate(year = year(mdy(date_start))) %>%
  select(site_name, year, transect, species, amount) %>%
  filter(site_name %in% c("Blake Island South", "Grain Terminal", "Freshwater Bay", "Magnolia", "Seattle Waterfront", "Wing Point")) %>%
  filter(year %in% c(2024, 2025))
kelp_data <- kelp_data %>%
  mutate(year = year(mdy(date_start))) %>%
  select(site_name, year, transect, species, amount, distance) %>%
  filter(site_name %in% c("Blake Island South", "Grain Terminal", "Freshwater Bay", "Magnolia", "Seattle Waterfront", "Wing Point")) %>%
  filter(year %in% c(2024, 2025))
invert_data <- invert_data %>%
  mutate(year = year(mdy(date_start))) %>%
  select(site_name, year, transect, species, amount, distance) %>%
  filter(site_name %in% c("Blake Island South", "Grain Terminal", "Freshwater Bay", "Magnolia", "Seattle Waterfront", "Wing Point")) %>%
  filter(year %in% c(2024, 2025))
```

species richness formats
```{r}
fish_richness <- select_fish_data %>%
  group_by(site_name, species, year) %>%
  summarise(amount = sum(amount, na.rm = TRUE), .groups = "drop")
kelp_richness <- kelp_data %>%
  group_by(site_name, species, year) %>%
  summarise(amount = sum(amount, na.rm = TRUE), .groups = "drop")
invert_richness <- invert_data %>%
  group_by(site_name, species, year) %>%
  summarise(amount = sum(amount, na.rm = TRUE), .groups = "drop")
```

now moving on to fish only for graphs...

Figure 29 - Centennial Park only. Abundance (or density, TBD) comparing '24/'25, stacking shallow/deep perhaps, by species

```{r}
CP_fish_data <- select_fish_data %>%
  filter(site_name %in% c("Grain Terminal")) %>%
  complete(year, species, site_name, transect, fill = list(amount = 0))
    


CP_fish_transect_data <- CP_fish_data %>%
  group_by(year, species, transect)%>%
  summarise(
    transect_amount = sum(amount, na.rm=TRUE),
    transect_density = transect_amount/120,
    .groups="drop")%>%
     mutate(
    depth_stratum = case_when(     
      transect %in% c(1:3, 7:12) ~ "deep",
      transect %in% c(4:6, 13:18) ~ "shallow",
      TRUE ~ NA_character_))

CP_fish_stratum_data <- CP_fish_transect_data %>%
  group_by(year, species, depth_stratum)%>%
  summarise(
    stratum_amount = sum(transect_amount, na.rm=TRUE),
    stratum_density = stratum_amount/9,
    stratum_cubic_density = stratum_density/120,
    transect_sd = sd(transect_amount),
    transect_density_sd = sd(transect_density),
    .groups="drop")

CP_fish_stratum_lowDensity <- CP_fish_stratum_data %>%
filter(!species %in% c("Kelp Perch", "Shiner Perch", "Striped Perch", "Pile Perch", "Forage Fish"))


CP_fish_stratum_perchAndFGF <- CP_fish_stratum_data %>%
filter(species %in% c("Kelp Perch", "Shiner Perch", "Striped Perch", "Pile Perch", "Forage Fish"))


```

initial test plot - disregard
```{r}
ggplot(CP_fish_stratum_data, aes(x = species, y = stratum_amount, fill = interaction(depth_stratum, year))) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(values = c("deep.2024" = "#1f77b4",      # dark blue
                               "shallow.2024" = "#aec7e8",    # light blue
                               "deep.2025" = "#ff7f0e",        # dark orange
                               "shallow.2025" = "#ffbb78"),    # light orange
                    labels = c("Deep 2024", "Shallow 2024", "Deep 2025", "Shallow 2025")) +
  labs(x = "Species",
       y = "Amount",
       fill = "Depth & Year",
       title = "Fish Abundance by Species, Depth, and Year at Grain Terminal") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),  # Rotate species names
        legend.position = "right")
```

low density fish plots (excluding perch & forage fish)
```{r}
ggplot(CP_fish_stratum_lowDensity, 
       aes(y=species, x=stratum_density, 
           fill=factor(year), 
           pattern = depth_stratum)) + 
  geom_bar_pattern(
    stat= "identity",
    position = position_dodge(width = .8, reverse=TRUE),
    color = "black",
    width = .8,
    pattern_fill = "black",
    pattern_density = 0.2,
    pattern_spacing = 0.02,
    pattern_angle = 45) +
  geom_errorbar(
    aes(xmin = pmax(stratum_density-transect_sd,0), xmax =stratum_density+transect_sd, 
                #group = interaction(depth_stratum, year)
        ),
    position = position_dodge(width=.8, reverse=TRUE),
    width = 0.2) +
  scale_fill_manual(values=c("2024" = "#66B2FF", "2025" = "#B8E39B")) +
  scale_pattern_manual(values = c("deep" = "stripe", "shallow" = "none")) +
  xlab(bquote(Density (m^-2))) +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_rect(color="black",
                                  fill=NA,
                                  size = 1),
        legend.position = c(0.98,0.5),
        legend.justification = c(1,0),
        legend.background = element_rect(fill = "white", color = NA),
        legend.margin = margin(4,4,4,4),
        # Increase legend text and key size
        legend.text = element_text(size = 10),          # Larger legend text
        legend.title = element_text(size = 11),         # Larger legend title
        legend.key.size = unit(1, "lines"),           # Larger legend keys
        legend.key.height = unit(0.8, "lines"),         # Adjust the height of legend keys (if necessary)
        legend.key.width = unit(1, "lines"),
        axis.title.y = element_text(size = 12),         # Larger x-axis label
        axis.title.x = element_text(size = 12),         # Larger y-axis label
        axis.text.y = element_text(size = 10),  # Larger x-axis tick labels
        axis.text.x = element_text(lineheight = 0.8, size = 10)) +       # Larger y-axis tick labels)
  geom_hline(yintercept = seq(0.5, length(unique(CP_fish_stratum_lowDensity$species)) - 0.5, by = 1), 
             color = "gray", 
             linetype = "solid", 
             linewidth = 0.5) +
  labs(y="Species", x="Density (m^2)") +
  guides(fill = guide_legend(title = "Year", order = 1,
                             override.aes = (list(
                               pattern = "none",
                               pattern_Density = 0,
                               pattern_fill = NA,
                               pattern_Spacing = 0,
                               pattern_angle = 0,
                               color = "black"))),
       pattern = guide_legend(title = "Depth Strata", order = 2,
                              override.aes = list(
                                fill = "white",
                                color = "black"
                              ))) +
  scale_x_continuous(expand=c(0,0),limits = c(0,2.5), breaks=seq(0,2.5,by=.25)) +
  scale_y_discrete(
    limits = rev(sort(unique(CP_fish_stratum_lowDensity$species))),  # Reverse alphabetical order
    labels = function(y) str_wrap(y, width = 14),
    expand = expansion(add = .5)) +
  coord_cartesian(xlim = c(0, 2.5))  #so error bars don't go below 0
```

high density fish plot (perch and forage fish)
```{r}
#assiging depth strata to transects
working_fish_data <- select_fish_data %>%
  group_by(site_name, species, year, transect)%>%
  summarise(amount = sum(amount, na.rm=TRUE), .groups = "drop") %>%
  mutate(
    depth_stratum = case_when(     
      transect %in% c(1:3, 7:12) ~ "deep",
      transect %in% c(4:6, 13:18) ~ "shallow",
      TRUE ~ NA_character_),
    density = amount/120)


#group by depth stratum, year, species; sum amounts
fish_strata <- working_fish_data %>%
  group_by(site_name, species, year, depth_stratum) %>%
  summarise(
    amount=sum(amount, na.rm=TRUE),
    density = sum(density, na.rm=TRUE)/3,
    .groups="drop")

#check on completeness of data
fish_check <- select_fish_data %>%
  group_by(site_name, year) %>%
  mutate(transect_count = n_distinct(transect))
```

